### ISSUE TITLE
docker-recommened with reclass ?

### ISSUE THREAD

**Issue by connaryscott** [deepmind/kapitan#337] opened 2019-08-18 16:48 UTC
**Describe the bug/feature**

Trying this:

https://kapitan.dev/#docker-recommended

```
C02TKBUNG8WN:kapitan chscott$ docker run -t --rm -v $(pwd):/src:delegated deepmind/kapitan -h
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/kapitan/__main__.py", line 17, in <module>
    from kapitan import cli
  File "/src/kapitan/cli.py", line 37, in <module>
    from kapitan.resources import (inventory_reclass, resource_callbacks,
  File "/src/kapitan/resources.py", line 27, in <module>
    import reclass
ModuleNotFoundError: No module named 'reclass'
```

It appears that python3 and reclass are not getting along:

```
02TKBUNG8WN:kapitan chscott$ docker run -it  --entrypoint bash -v $(pwd):/src:delegated deepmind/kapitan
bash-5.0# pip install reclass
Collecting reclass
  Downloading https://files.pythonhosted.org/packages/e6/e2/7ab398b65da859966784f81145efa37d577005fc43432dd7b0f252196a98/reclass-1.4.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ao470mow/reclass/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ao470mow/reclass/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ao470mow/reclass/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ao470mow/reclass/setup.py", line 10, in <module>
        from reclass.version import *
      File "/tmp/pip-install-ao470mow/reclass/reclass/__init__.py", line 10, in <module>
        from output import OutputLoader
    ModuleNotFoundError: No module named 'output'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

python v2 does appear to install this module and reclass seems like an old project.

**To Reproduce**
1. https://kapitan.dev/#docker-recommended
2. See error above

**Expected behavior**
The kapitan help output

**Screenshots**
See above

** If it's a bug (please complete the following information):**
- using your published container, latest and earlier ones.

**Additional context**

**Comment by ramaro** [comment] 2019-08-18 21:18
@connaryscott thanks for reporting!

What version are you running? Can you ensure you pull the latest?
I can't reproduce it. It works for me:

```shell
$ docker run -t --rm -v $(pwd):/src:delegated deepmind/kapitan -h 
latest: Pulling from deepmind/kapitan                                                                                  
050382585609: Pull complete
dac2222ca532: Pull complete
...
usage: kapitan [-h] [--version]
               {eval,compile,inventory,searchvar,secrets,lint,init,validate}
               ...

Generic templated configuration management for Kubernetes, Terraform and other
things
...
```

**Comment by connaryscott** [comment] 2019-08-19 16:22
Interesting so it works "now".....

I just retried it, did nothing else to improve my situation.  Perhaps
the"latest" was transiently bad?

**Comment by ramaro** [comment] 2019-08-19 16:23
Yep, sounds like something transient. Closing.

**Closed by ramaro** 2019-08-19 16:23 UTC
