### ISSUE TITLE
Install deps  doesn't return proper pkgs list 

### ISSUE THREAD

**Issue by harsh-98** [deepmind/kapitan#261] opened 2019-04-05 07:02 UTC
**Describe the bug/feature**
In setup.py the install_deps function return pkgs and new_links list. It simply reads the requirements.txt and return lines in list form. It doesn't check whether that line is a comment or not. 

**To Reproduce**
1. Go to setup.py
2. install_deps doesn't directly print the json output for that I simply add:
`import json; print(json.dumps(pkgs, indent=4, sort_keys=True))`
This is done just for showing the returned value of pkgs.
![comment](https://user-images.githubusercontent.com/23700929/55609268-e4b41580-579d-11e9-9e2d-f296aa99ed77.png)

3. As you can see comments are also in pkgs list.

**Expected behavior**
Pkgs list should not contain any comments or empty string.

**Comment by uberspot** [comment] 2019-04-05 09:23
The expected behaviour of this is actually allowing comments as well. 
From https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies 
`# comment lines and \ continuations are allowed in requirement strings` 
So we don't actually need to fix this since comments improve readability. :+1: 
Closing for now.

**Closed by uberspot** 2019-04-05 09:23 UTC
