### ISSUE TITLE
[bug] Some strings are handled as booleans instead of strings

### ISSUE THREAD

**Issue by skinny** [deepmind/kapitan#311] opened 2019-06-19 12:20 UTC
**Describe the bug/feature**
I needed an environment variable with the value of `Y` in one of my kubernetes templates. When I tried to generate it based on the followin jsonnet snippet:

```  ...
env+: [
  { name: 'ACCEPT_EULA', value: 'Y' },
]
...
```

It gets rendered by kapitan as : 

```
- name: ACCEPT_EULA
  value: Y
```

This yaml is not accepted by `kubectl`/Kubernetes because it expects a string value here and apparently the `Y` character (without quotes) is treated as a boolean instead of a string somewhere during the processing of kapitan : 

```for: "compiled/euw-ci/manifests/sql-server-deployment.yml": unrecognized type: string```

See https://yaml.org/type/bool.html on which strings are treated as booleans

**Expected behavior**
String values like 'Y' should be rendered as 'Y' in the output file, or at least there must be a way to escape the current behaviour.

**Comment by gburiola** [comment] 2019-06-19 13:24
This is very likely caused by a bug in PyYaml
https://github.com/yaml/pyyaml/issues/247

It does the right thing for all variations listed on https://yaml.org/type/bool.html, expect for the single char `Y` or `N`

```
$ kapitan eval --output yaml <(echo '{ "value": "yes" }')
value: 'yes'

$ kapitan eval --output yaml <(echo '{ "value": "Y" }')
value: Y
```

**Comment by ramaro** [comment] 2019-10-17 16:40
I'm closing this as this is not a bug and is indeed the expected behavior.

**Closed by ramaro** 2019-10-17 16:40 UTC
Labels: bug
